# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigs', '0004_auto_20170902_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='personoptions',
            name='category',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personoptions',
            name='city',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personoptions',
            name='options',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personoptions',
            name='subcategory',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
