# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigs', '0006_personoptions_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='personoptions',
            name='keyword',
            field=models.CharField(default="0", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personoptions',
            name='stop_word',
            field=models.CharField(default="0", max_length=250),
            preserve_default=False,
        ),
    ]
