# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('craigs', '0009_remove_personoptions_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='personoptions',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
