# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigs', '0014_auto_20170912_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaloptions',
            name='subcategory',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='subcategoryoptions',
            name='subcategory_for_frontend',
            field=models.CharField(max_length=250),
        ),
    ]
