# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigs', '0015_auto_20170913_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityoptions',
            name='city_for_frontend',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='options',
            name='front_category',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='options',
            name='front_subcategory',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
