# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigs', '0017_auto_20170915_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personoptions',
            name='options',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
