# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigs', '0019_auto_20170922_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='personoptions',
            name='url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
