# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigs', '0020_personoptions_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personoptions',
            name='category',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='personoptions',
            name='city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='personoptions',
            name='subcategory',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
