# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigs', '0021_auto_20171003_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityoptions',
            name='state',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cityoptions',
            name='city',
            field=models.CharField(max_length=250),
        ),
    ]
