# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigs', '0022_auto_20171003_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityoptions',
            name='city_for_frontend',
            field=models.CharField(max_length=250),
        ),
    ]
